### ISSUE TITLE
مشکل در خروجی پیام #30001

### ISSUE THREAD

**Issue by geeksesi** [RooyeKhat-Media/iGap-API#2]
سلام. 
من می خواهم با "پی‌اچ‌پی" از این سرویس استفاده کنم
برای اتصال به وب سوکت از این کتابخونه استفاده می کنم:
https://github.com/Textalk/websocket-php
وقتی اتصال برقرار میشه طبق گفته شما باید پیغامی حاوی این موارد داخلش باشه : 
https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/proto/ConnectionSecuringResponse.md
اما پیغامی که من دریافت می کنم به شکل زیر است : 
https://paste.ubuntu.com/p/xKpkxYzvwQ/
من به دنبال 
symmetric_key_length
هستم برای ساخت متن رندم طبق این سند:
https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/Securing.md
میشه لطفا راهنمایی کنید که این مقدار کجای این خروجی قرار داره ؟

**Comment by amereii** [comment]
سلام

پیام هایی که از طریق وب سوکت رد و بدل میشن تماما بصورت باینری هستن اول اینجا رو ببینید
https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/Transmission.md#format

شما باید بصورت زیر عمل کنید
* دو بایت اول و بقیه بایت ها رو جدا کنید
* دوبایت اول رو بصورت
 little endian byte order
 پردازش کنید و این رو ما بنام
 actionId 
میشناسیم
*  در زبان 
PHP
 تابع
http://php.net/manual/en/function.unpack.php
 براتون این کار رو میکنه اگه آشنایی ندارید اول
 http://php.net/manual/en/function.pack.php
 رو بخونید

* حالا که میدونید 
actionId
 چی هست ، باید مطابق جدول 
https://github.com/RooyeKhat-Media/iGap-API/blob/master/docs/guide/v1/proto/README.md 
ببینید بقیه بایت هایی که جدا کردید رو چطوری باید پردازش کنید

برای مثال اگر 30001 دریافت شد یعنی بقیه بایت ها آبجکت
 ConnectionSecuringResponse
 هستند
ما از پروتکل بافر استفاده میکنیم شما اول باید پروتوبافر ها رو برای پی اچ پی کامپایل کنید

اینجا رو بخونید
https://github.com/google/protobuf
https://developers.google.com/protocol-buffers/

فایل های پروتوبافر ما اینجا هستند
https://github.com/RooyeKhat-Media/iGap-API/tree/master/app/assets/proto

بعد کامپایل برای شما کلاس های پی اچ پی ساخته میشه ، با توجه به 
actionId
 باید از کلاس مربوطه یه نمونه بسازید و با بایت ها پر کنید و در نهایت میتونید 
symmetric_key_length 
رو بخونید

**Comment by geeksesi** [comment]
خیلی ممنون بابت پاسختون
توضیحاتی که دادید رو استفاده کردم یه سری مشکلاتی داشتم که حل کردم فقط یک جا رو متوجه نمی شم هرچقدر هم سرچ می کنم چیزی دستگیرم نمی شه.
خب من 
 actionId 
رو گرفتم و 30001 هم خروجیش بود
حالا دقیقا متوجه نمی شم بقیه خروجی رو باید چیکار کنم..
پروتوبافر هاتون رو هم کامپایل کردم.
من با این دستور اکشن ایدی رو استخراج کردم
`unpack("vactionId/c*", $data);`
اون / برای ادامه کد هست که من نمی دونستم چه فرمتی باید برای استخراج ادامه بایت ها در نظر بگیرم
فرمت های موجود توی دایکیومنت پی‌اچ‌پی رو هم امتحان کردم هر کدوم یه نوع خروجی داشتند ولی خب متوجه نشدم کدوم درسته...
اصلا دارم درست عمل می کنم ؟ یعنی باید ادامه بایت ها رو به این شیوه ان‌پک کنم یا خروجی قبل رو بدم به تابع 
`Proto\ConnectionSecuringResponse::setResponse `
؟
اگه ممکنه یه راهنمایی بفرمایید :)

**Comment by amereii** [comment]
بهتره اینجا رو بخونید
https://developers.google.com/protocol-buffers/docs/reference/php-generated

بعد از اینکه دو بایت و بقیه بایت ها رو جدا کردید  اینطوری پروتوبافر رو ایجاد کنید

```php
$response = new \Proto\ConnectionSecuringResponse();
try {
  $response->mergeFromString($payload);
} catch (Exception $e) {
  // Handle parsing error from invalid data.
  ...
}

echo $response->getSymmetricKeyLength();
```

بهتره یه جدول درست کنید و اتوماتیک هندل کنید مثلا اینطوری

```php
const CONNECTION_SECURING_RESPONSE = 30000;

$actions = [
    CONNECTION_SECURING_RESPONSE =>'ConnectionSecuringResponse',
   // همه اکشن ها رو لیست میکنیم
];

$responseClass = '\Proto\\'.$actions[$actionId];// اکشن آی دی هم معلومه
$response = new $responseClass();
try {
    $response->mergeFromString($payload);
} catch (Exception $e) {
    // Handle parsing error from invalid data.
    ...
}

```
